### ISSUE TITLE
Clone This Repo To HuggingFace

### ISSUE THREAD

**Issue by jrittvo** [Zabriskije/CoreML-VAEs#1]
This is very useful stuff to have together in one place.  I think HuggingFace would tap and reach a wider audience,  making this easier to grow with community additions.

**Comment by Zabriskije** [comment]
It's already on [Hugging Face](https://huggingface.co/Zabriskije/CoreML-VAEs) 🥳

**Comment by jrittvo** [comment]
You the man!
